language: python
python:
  - "3.5"
  - "nightly"
env:
  - DJANGO=1.8
install:
  - pip install pep8
  - pip install -q Django==$DJANGO
script:
  - pep8 --exclude=meta_efa/meta_efa/ --exclude=meta_efa/main/migrations/ meta_efa/
